services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://api.starboy.ir}
        image: starboy:latest
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "${HOST_PORT:-3000}:3000"
