services:
    web:
        image: ${DOCKERHUB_USERNAME:-rodxa}/${IMAGE_NAME:-starboy}:${IMAGE_TAG:-latest}
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "${HOST_PORT:-3000}:3000"
